version: '3.8'
services:
  inventoryservice:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
