version: '3.8'
services:
  inventoryservice:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgresdb
